### ISSUE TITLE
Guardian Fins are dropping even with the item disabled in items.yml

### ISSUE THREAD

**Issue by Boomer-1** [SchnTgaiSpock/Gastronomicon#10]
## Description (Required)

I disabled guardian fins in the items.yml file, yet they continue to drop from guardians

## Steps to reproduce the Issue (Required)

kill a guardian, you get the fins

## Expected behavior (Required)

with it disabled i expect it not to drop

## Server Log / Error Report

no errors.

## Environment (Required)

- Minecraft Version: 1.20.1
- Slimefun Version: dev 1097
- Plugin Version: Dev 8

**Comment by SchnTgaiSpock** [comment]
sorry, been a bit busy, for now you can set `drops.mob-kill-chance` to 0 in the config

**Comment by SchnTgaiSpock** [comment]
fixed in latest build https://github.com/SchnTgaiSpock/Gastronomicon/releases/tag/v1.0.6
