### ISSUE TITLE
Buckets of water get consumed by the machine

### ISSUE THREAD

**Issue by satanplaysmc** [SchnTgaiSpock/Gastronomicon#15]
## Description (Required)
When making recipes which use water buckets like soup the machines eat up the waterbucket rather than spitting out an empty one. This makes the production of certain foods a rather costly endeavour as iron is a rather expensive resource, meanwhile other slimefun addons usually don't eat up the waterbuckets.

## Expected behavior (Required)
Empty buckets to come out after a recipe with a waterbucket is made.

**Comment by SchnTgaiSpock** [comment]
The bucket is refunded when you eat the soup but i could be wrong lemme check

**Comment by SchnTgaiSpock** [comment]
yeah i was wrong, ill look into it

**Comment by SchnTgaiSpock** [comment]
should be fixed now in build 3

**Comment by SchnTgaiSpock** [comment]
please open a separate issue and fill in the required info
