### ISSUE TITLE
Water bottles get consumed by machine

### ISSUE THREAD

**Issue by satanplaysmc** [SchnTgaiSpock/Gastronomicon#18]
## Description (Required)
When making recipes which use water bottles like dough the machines eat up the  water bottles rather than spitting out an empty one. This makes producing certain foods a rather costly endeavour as glass is a rather expensive resource, meanwhile other slimefun addons usually don't eat up the  water bottles.

## Steps to reproduce the Issue (Required)
Put a water bottle and wheat flour in an electric kitchen, as it produces 1 dough it also eats up the bottle.
## Expected behavior (Required)
One dough to be produced without eating up the bottle. 

## Environment (Required)

![image](https://github.com/user-attachments/assets/8c6353d6-3406-449c-9c5d-3535c26bae80)

**Comment by SchnTgaiSpock** [comment]
sorry for the late reply, should be fixed in Dev 5 now
