### ISSUE TITLE
Ingredients drop when Event is Cancelled

### ISSUE THREAD

**Issue by JustAHuman-xD** [SchnTgaiSpock/Gastronomicon#19]
## Description (Required)
In creative mode holding a sword on meta's test server, if you try to break grass or any similar block the event is cancelled. However, if you just spam it gastronomicon still drops ingredients from it.

## Steps to reproduce the Issue (Required)
1. Go into creative
2. Hold a sword
3. Spam left click grass
4. Watch
(I'll make a vid when I can)

## Expected behavior (Required)
No ingredients to drop

## Server Log / Error Report
No errors

## Environment (Required)
- Minecraft Version: 1.20.6
- Slimefun Version: Dev-1156
- Plugin Version: Dev-4

**Comment by SchnTgaiSpock** [comment]
should be fixed in dev 5
