### ISSUE TITLE
Protection Hooks/checks needed

### ISSUE THREAD

**Issue by Silentassassin939** [SchnTgaiSpock/Gastronomicon#3]
## Description (Required)
Trying to break grass/blocks in areas that the player can't break them because of various protection plugins still have a chance of dropping seeds/drops

## Expected behavior (Required)

No seeds/drops being spawned when a protection plugin stops the break(in this case the plugin was towny)

## Environment (Required)
![image](https://github.com/SchnTgaiSpock/Gastronomicon/assets/133166446/5b27a7fb-2fe8-4864-8e33-b150a4cec438)

**Comment by SchnTgaiSpock** [comment]
should be fixed in build #4
