### ISSUE TITLE
Plants Reverting back to Vanilla

### ISSUE THREAD

**Issue by mitchngwen** [SchnTgaiSpock/Gastronomicon#4]
## Description (Required)
When you plant seeds from this plugin they revert back to vanilla plants

## Steps to reproduce the Issue (Required)
installed on paper 1.19.4. plant a seed from this plugin bonemeal it and you get vanilla plant/food

## Expected behavior (Required)
I expect to grow food from this plugin

## Server Log / Error Report
none

## Environment (Required)
This Server uses the following setup of Slimefun:\nPaper git-Paper-530 (MC: 1.19.4)\nSlimefun DEV - 1050 (git 22a7f422)\nMetrics-Module #28\nJava 18\n\nInstalled Addons: (36)\n  Networks vDEV - 46 (git 9368ce6b)\n  CrystamaeHistoria vDEV - 81 (git 0c0efa95)\n  ShopGUIPlus v1.83.1\n  ExtraTools vDEV - 36 (git 922c0324)\n  RelicsOfCthonia vDEV - 8 (git a7ef6cb6)\n  FoxyMachines vDEV - 62 (git ab78d44e)\n  FNAmplifications vDEV - 89 (git 4ef745b3)\n  DynaTech vDEV - 194 (git 990c942e)\n  SimpleMaterialGenerators vDEV - 4 (git 5543cc8f)\n  ExtraGear vDEV - 13 (git c62047e2)\n  CMILib v1.2.5.3\n  InfinityExpansion vDEV - 140 (git 0098d2fb)\n  Supreme vDEV - 29 (git f9e70053)\n  SlimyTreeTaps vDEV - 20 (git 963f0383)\n  MobCapturer vDEV - 26 (git e0f006c2)\n  FlowerPower vDEV - 15 (git 35662ced)\n  SpiritsUnchained vDEV - 22 (git 28e031e0)\n  Galactifun vDEV - 75 (git 1fdb2dd0)\n  FluffyMachines vDEV - 130 (git 01c839cc)\n  DyedBackpacks vDEV - 17 (git 8b329e96)\n  Gastronomicon vDEV - 4 (git a6c06219)\n  Cultivation vDEV - 9 (git df727409)\n  SmallSpace vDEV - 12 (git 6b372f8c)\n  AlchimiaVitae vDEV - 24 (git 6950e5d2)\n  EcoPower vDEV - 5 (git 5c1ecd68)\n  HotbarPets vDEV - 38 (git fa6c871d)\n  ExoticGarden vDEV - 78 (git 7f9a5f63)\n  DankTech2 vDEV - 8 (git f2a8ab1f)\n  Liquid vDEV - 14 (git 0f5346bf)\n  LiteXpansion vDEV - 188 (git c0cb079e)\n  SimpleUtils vDEV - 15 (git 4250fd5e)\n  ElementManipulation vDEV - 28 (git 2b469991)\n  Netheopoiesis vDEV - 18 (git 9d12cc6f)\n  SimpleStorage vDEV - 10 (git ea5e5637)\n  PotionExpansion vDEV - 5 (git e2cfcd8a)\n  SlimyRepair vDEV - 4 (git 790c41cb)
[21:48:58] [Render thread/INFO]: [System] [CHAT] [X] Join a /Class ➼ fogMidnight: hello?/

- Minecraft Version: 1.19.4
- Slimefun Version: Slimefun DEV - 1050
- Plugin Version: Gastronomicon vDEV - 4 (git a6c06219)

**Comment by mitchngwen** [comment]
Could I get some help with this one? I would love to be able to play with this addon.

**Comment by SchnTgaiSpock** [comment]
did you quickly break and place a plant in that spot? if so thats probably a blockstorage issue (w/ main sf)

**Comment by SchnTgaiSpock** [comment]
another possible indication that its a blockstorage issue is if a seed pops out of nowhere when you place the plant

**Comment by SchnTgaiSpock** [comment]
i have tested on 1.19.4 and cant duplicate this issue
