### ISSUE TITLE
Unable to make Scrambled Eggs

### ISSUE THREAD

**Issue by twomuchlulz** [SchnTgaiSpock/Gastronomicon#8]
Both the recipes for Toast and Fried eggs show that you have to cook it with low heat with the Multi-stove. In practice however, medium heat is required, leading to a conflict between the recipe for Fried eggs and Scrambled eggs. Making Scrambled eggs and any other food items that require Scrambled eggs is impossible right now.

**Comment by SchnTgaiSpock** [comment]
should be fixed in v1.0.4 (DEV 7)
