### ISSUE TITLE
1.18 Gastronomicon disabled

### ISSUE THREAD

**Issue by xMikux** [SchnTgaiSpock/Gastronomicon#9]
## Description (Required)
Using 1.18 (or maybe below version), will cause error and disable the plugin.

## Steps to reproduce the Issue (Required)
1. Setup 1.18 Server
2. Install Slimefun and Gastronomicon
3. See the error

## Expected behavior (Required)
Should be available enabled on 1.18 version

## Server Log / Error Report
https://pastebin.com/gh9xGeKf

## Environment (Required)
![image](https://github.com/SchnTgaiSpock/Gastronomicon/assets/26039249/d3dfd082-ee4c-4d33-bf96-91af48e6871b)

**Comment by SchnTgaiSpock** [comment]
should be fixed in 1.0.5 (build 8)
